### ISSUE TITLE
Possible destructive mod.

### ISSUE THREAD

**Issue by Megaf** [bdjnk/glow#2]
I believe this mod is replacing placed blocks, on buildings for example, by the things it generates, like fireflies, and then living air where before a node used to be.

**Comment by bdjnk** [comment]
I've not had this experience, and from looking at the code it seems impossible. If you can provide additional details, like minetest version and glow version, that might help.

**Comment by Megaf** [comment]
If not caused by glow, then I dont know, I noticed that nodes begun to vanish close to glow mushrooms. But I can be mistaken.
Latest master from GIT, for mt game, mt and glow.

**Comment by bdjnk** [comment]
Reexamining the mushroom code, I do see a possibility for nodes to be overwritten. I'll confirm and correct if necessary

**Comment by bdjnk** [comment]
Confirmed, thanks! Corrected by 76b7a3a.

**Comment by Megaf** [comment]
You're welcome, thanks for fixing.
